apiVersion: apps/v1
kind: Deployment

metadata:
  name: cloudops-platform
  labels:
    app: cloudops-platform

spec:
  replicas: 2

  selector:
    matchLabels:
      app: cloudops-platform

  template:
    metadata:
      labels:
        app: cloudops-platform

    spec:
      containers:
        - name: cloudops-platform
          image: 979214968440.dkr.ecr.ap-south-1.amazonaws.com/cloudops-platform:1.0

          ports:
            - containerPort: 4000

          env:
            - name: PORT
              value: "4000"

            - name: NODE_ENV
              value: "production"
